server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.117.135.149:3306/hospital?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
  # email config
  #邮箱配置 开启smtp服务    password为授权码
  mail:
    host: smtp.qq.com
    username: jason72411@qq.com
    password: tbrvsoqtasnbbeid
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

swagger:
  enabled: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case=true:
  mapper-locations: classpath:mapper/*.xml


#用户上传文件存储路径
file:
  # file-save-path: E:/upload/images/
  file-save-path: /Users/lionel_xyl/Downloads/upload/